/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersNewRouteImport } from './routes/users/new'
import { Route as UsersListRouteImport } from './routes/users/list'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as UsersUpdateUserIdRouteImport } from './routes/users/update.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersListRoute = UsersListRouteImport.update({
  id: '/users/list',
  path: '/users/list',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUpdateUserIdRoute = UsersUpdateUserIdRouteImport.update({
  id: '/users/update/$userId',
  path: '/users/update/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/list': typeof UsersListRoute
  '/users/new': typeof UsersNewRoute
  '/users/update/$userId': typeof UsersUpdateUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/list': typeof UsersListRoute
  '/users/new': typeof UsersNewRoute
  '/users/update/$userId': typeof UsersUpdateUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/list': typeof UsersListRoute
  '/users/new': typeof UsersNewRoute
  '/users/update/$userId': typeof UsersUpdateUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/users/$userId'
    | '/users/list'
    | '/users/new'
    | '/users/update/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/users/$userId'
    | '/users/list'
    | '/users/new'
    | '/users/update/$userId'
  id:
    | '__root__'
    | '/'
    | '/users/$userId'
    | '/users/list'
    | '/users/new'
    | '/users/update/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersListRoute: typeof UsersListRoute
  UsersNewRoute: typeof UsersNewRoute
  UsersUpdateUserIdRoute: typeof UsersUpdateUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/list': {
      id: '/users/list'
      path: '/users/list'
      fullPath: '/users/list'
      preLoaderRoute: typeof UsersListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/update/$userId': {
      id: '/users/update/$userId'
      path: '/users/update/$userId'
      fullPath: '/users/update/$userId'
      preLoaderRoute: typeof UsersUpdateUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  UsersListRoute: UsersListRoute,
  UsersNewRoute: UsersNewRoute,
  UsersUpdateUserIdRoute: UsersUpdateUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
